triggers:
  - type: meya.keyword
    properties:
        keyword: note
states:
    note:
        component: human.note
        properties:
            text: "They are a great customer! Treat them right."